---
steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'  
    args: 
      - '-c'
      - | 
          echo "hello1" > obj1.txt
          echo "hello" > obj.txt
          ls
          pwd

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'  
    args: 
      - '-c'
      - | 
          gcloud config list
          gcloud storage cp obj.txt gs://artifacts-1
          gcloud storage cp obj1.txt gs://artifacts-1
          
options:
  logging: CLOUD_LOGGING_ONLY
